name = "b2b-lead-generation-platform"
main = "./build/server/index.js"
compatibility_date = "2024-11-15"
compatibility_flags = ["nodejs_compat"]

# React Router 7 builds everything for us
[build]
command = "npm run build"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "lead-generation-db"
database_id = "a966011e-98ea-48b3-9633-4bce1b200438"

# AI Integration
[ai]
binding = "AI"

# Environment Variables (set these in Cloudflare Dashboard > Workers > Settings > Variables)
# META_ACCESS_TOKEN (secret)
# META_AD_ACCOUNT_ID (secret)
# OPENAI_API_KEY (secret)
# ANTHROPIC_API_KEY (secret)
# JWT_SECRET (secret)

[env.production]
vars = { 
  ENVIRONMENT = "production"
}

[env.development] 
vars = { 
  ENVIRONMENT = "development"
}
