name = "b2b-lead-generation-platform"
main = "./workers/app.ts"
compatibility_date = "2024-11-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Assets configuration for React Router v7
[assets]
directory = "./build/client"
binding = "ASSETS"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "lead-generation-db"
database_id = "a966011e-98ea-48b3-9633-4bce1b200438"

# AI Integration
[ai]
binding = "AI"

# Environment Variables (set via wrangler secret)
# META_ACCESS_TOKEN
# META_AD_ACCOUNT_ID  
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# JWT_SECRET

# CORS Configuration
[env.production]
vars = { 
  ENVIRONMENT = "production",
  API_URL = "https://your-domain.com"
}

[env.development] 
vars = { 
  ENVIRONMENT = "development",
  API_URL = "http://localhost:8787"
}
