name = "b2b-lead-generation-platform"
main = "dist/index.js"
compatibility_date = "2024-11-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "lead-generation-db"
database_id = "your-database-id-here"

# AI Integration
[ai]
binding = "AI"

# Environment Variables (set via wrangler secret)
# META_ACCESS_TOKEN
# META_AD_ACCOUNT_ID  
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# JWT_SECRET

# CORS Configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development] 
vars = { ENVIRONMENT = "development" }